spring:
  application:
    name: Restaurant

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  error:
    include-stacktrace: always
  port: 1212

app:
  jwt:
    secret: BaktygulJk
